version: "3.8"
services:
  sql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_HOST: "sql"
      MYSQL_DATABASE: "pokemonsdatabase"

  mongo:
    image: mongo

  server:
    build: .
    depends_on:
      - sql
      - mongo
    ports:
      - "8000:8000"