version: "3.8"
services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_HOST: "database"
      MYSQL_DATABASE: "pokemonsdatabase"

  server:
    build: .
    depends_on:
      - database
    ports:
      - "8000:8000"